# Generated by Django 3.1.4 on 2020-12-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areasproy',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('supconstsnb', models.FloatField(blank=True, db_column='supConstSNB', null=True)),
                ('supconstbnb', models.FloatField(blank=True, db_column='supConstBNB', null=True)),
                ('supdesplante', models.FloatField(blank=True, db_column='supDesplante', null=True)),
                ('suppavimentos', models.FloatField(blank=True, db_column='supPavimentos', null=True)),
                ('supverdeperm', models.FloatField(blank=True, db_column='supVerdePerm', null=True)),
                ('supverdeimper', models.FloatField(blank=True, db_column='supVerdeImper', null=True)),
                ('supotraslibres', models.FloatField(blank=True, db_column='supOtrasLibres', null=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('stampcrea', models.DateTimeField(blank=True, db_column='stampCrea', null=True)),
                ('stampmod', models.DateTimeField(blank=True, db_column='stampMod', null=True)),
            ],
            options={
                'db_table': 'areasProy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Obs',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('obs', models.TextField(blank=True, null=True)),
                ('stampcrea', models.DateTimeField(blank=True, db_column='stampCrea', null=True)),
                ('stampmod', models.DateTimeField(blank=True, db_column='stampMod', null=True)),
                ('fk_creador', models.IntegerField(blank=True, null=True)),
                ('fk_modif', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'obs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('cliente', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechainicio', models.DateField(blank=True, db_column='fechaInicio', null=True)),
                ('fechafin', models.DateField(blank=True, db_column='fechaFin', null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('avance', models.FloatField(blank=True, null=True)),
                ('fk_predio', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('stampcrea', models.DateTimeField(blank=True, db_column='stampCrea', null=True)),
                ('stampmod', models.DateTimeField(blank=True, db_column='stampMod', null=True)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
    ]
