# Generated by Django 3.1.4 on 2020-12-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20201216_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoproyecto',
            old_name='tipo',
            new_name='clave',
        ),
        migrations.RenameField(
            model_name='tipoproyecto',
            old_name='nombrelargo',
            new_name='nombre',
        ),
    ]
