# Generated by Django 3.1.4 on 2020-12-17 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20201217_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fk_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proyecto.tipoproyecto'),
        ),
    ]
