# Generated by Django 3.1.4 on 2021-02-24 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('fk_espacio_padre', models.ForeignKey(blank=True, db_column='fk_espacioPadre', null=True, on_delete=django.db.models.deletion.CASCADE, to='espacios.espacio')),
            ],
            options={
                'db_table': 'espacios',
            },
        ),
        migrations.CreateModel(
            name='Zonificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('clave', models.CharField(blank=True, max_length=120, null=True)),
                ('ordenamiento', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('espacio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='espacios.espacio')),
                ('uso_principal', models.CharField(blank=True, max_length=70, null=True)),
                ('niveles_snb', models.IntegerField(blank=True, default=1, null=True)),
                ('niveles_bnb', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('espacios.espacio',),
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('espacio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='espacios.espacio')),
                ('cuenta_catastral', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('espacios.espacio',),
        ),
        migrations.CreateModel(
            name='Superficie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, choices=[('1', 'total'), ('2', 'construida'), ('3', 'desplante'), ('4', 'libre'), ('5', 'verde'), ('6', 'pavimentada'), ('7', 'permeable'), ('8', 'BNB'), ('9', 'SNB'), ('10', 'cajones_est'), ('40', 'restricción'), ('20', 'max_desplante'), ('21', 'max_const'), ('22', 'libre_req'), ('30', 'cajones_est_req'), ('50', 'otra')], default=1, max_length=4, null=True)),
                ('area', models.FloatField(blank=True, default=0.0, null=True, verbose_name='m²')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.espacio')),
            ],
        ),
    ]
