# Generated by Django 3.1.4 on 2021-02-24 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directorio', '0001_initial'),
        ('proyectos', '0001_initial'),
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='fk_obs',
            field=models.ManyToManyField(blank=True, to='proyectos.Obs'),
        ),
        migrations.AddField(
            model_name='predio',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.direccion'),
        ),
        migrations.AddField(
            model_name='predio',
            name='zonificaciones',
            field=models.ManyToManyField(blank=True, to='espacios.Zonificacion'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='proyecto',
            field=models.ManyToManyField(blank=True, to='proyectos.Proyecto'),
        ),
    ]
