# Generated by Django 3.1.4 on 2020-12-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='Espacio',
            table='espacio',
        ),
    ]
