# Generated by Django 3.1.4 on 2021-01-17 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_delete_areasproy'),
        ('directorio', '0007_auto_20210117_0626'),
        ('espacios', '0002_auto_20201227_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonificacion',
            fields=[
                ('espacio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='espacios.espacio')),
                ('clave', models.CharField(blank=True, max_length=120, null=True)),
                ('ordenamiento', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('espacios.espacio',),
        ),
        migrations.AlterModelOptions(
            name='espacio',
            options={},
        ),
        migrations.CreateModel(
            name='Superficie',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, choices=[('1', 'total'), ('2', 'construida'), ('3', 'desplante'), ('4', 'libre'), ('5', 'verde'), ('6', 'pavimentada'), ('7', 'permeable'), ('8', 'BNB'), ('9', 'SNB'), ('10', 'cajones_est'), ('40', 'restricción'), ('20', 'max_desplante'), ('21', 'max_const'), ('22', 'libre_req'), ('30', 'cajones_est_req'), ('50', 'otra')], default=1, max_length=4, null=True)),
                ('area', models.FloatField(blank=True, default=0.0, null=True, verbose_name='m²')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.espacio')),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('espacio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='espacios.espacio')),
                ('cuenta_predial', models.CharField(blank=True, max_length=120, null=True)),
                ('direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directorio.direccion')),
                ('proyecto', models.ManyToManyField(blank=True, to='proyectos.Proyecto')),
                ('zonificaciones', models.ManyToManyField(blank=True, to='espacios.Zonificacion')),
            ],
            options={
                'abstract': False,
            },
            bases=('espacios.espacio',),
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('espacio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='espacios.espacio')),
                ('uso_principal', models.CharField(blank=True, max_length=70, null=True)),
                ('niveles_snb', models.IntegerField(blank=True, default=1, null=True)),
                ('niveles_bnb', models.IntegerField(blank=True, null=True)),
                ('proyecto', models.ManyToManyField(blank=True, to='proyectos.Proyecto')),
            ],
            options={
                'abstract': False,
            },
            bases=('espacios.espacio',),
        ),
    ]
