# Generated by Django 3.1.4 on 2021-01-17 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_delete_areasproy'),
        ('espacios', '0003_auto_20210117_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espacio',
            name='alturasnb',
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='sup',
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='supconst',
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='supdesp',
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='tipo',
        ),
        migrations.AddField(
            model_name='espacio',
            name='fk_espaciopadre',
            field=models.ForeignKey(blank=True, db_column='fk_espacioPadre', null=True, on_delete=django.db.models.deletion.CASCADE, to='espacios.espacio'),
        ),
        migrations.AddField(
            model_name='espacio',
            name='fk_obs',
            field=models.ManyToManyField(blank=True, to='proyectos.Obs'),
        ),
        migrations.AddField(
            model_name='espacio',
            name='stamp_crea',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='espacio',
            name='stamp_mod',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterModelTable(
            name='espacio',
            table='espacio',
        ),
    ]
