# Generated by Django 3.1.4 on 2021-01-17 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0004_auto_20210117_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='stamp_crea',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterModelTable(
            name='espacio',
            table='espacios',
        ),
    ]
