# Generated by Django 3.1.4 on 2021-01-18 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0005_auto_20210117_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='proyecto',
        ),
    ]
