# Generated by Django 3.1.4 on 2021-01-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0006_remove_predio_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espacio',
            old_name='fk_espaciopadre',
            new_name='fk_espacio_padre',
        ),
        migrations.RenameField(
            model_name='predio',
            old_name='cuenta_predial',
            new_name='cuenta_catastral',
        ),
        migrations.RemoveField(
            model_name='predio',
            name='zonificaciones',
        ),
        migrations.DeleteModel(
            name='Zonificacion',
        ),
    ]
