# Generated by Django 3.1.4 on 2021-01-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0007_auto_20210118_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonificacion',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('clave', models.CharField(blank=True, max_length=120, null=True)),
                ('ordenamiento', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='predio',
            name='zonificaciones',
            field=models.ManyToManyField(blank=True, to='espacios.Zonificacion'),
        ),
    ]
