# Generated by Django 3.1.4 on 2020-12-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.TextField(max_length=35)),
                ('nombrelargo', models.TextField()),
                ('plazoentrega', models.IntegerField(blank=True, null=True, verbose_name='Plazo_días_hábiles')),
            ],
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'managed': True},
        ),
    ]
