# Generated by Django 3.1.4 on 2020-12-28 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_auto_20201228_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='fechafin',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fechainicio',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fk_proyectopadre',
            new_name='fk_proyecto_padre',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='stampcrea',
            new_name='stamp_crea',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='stampmod',
            new_name='stamp_mod',
        ),
    ]
