# Generated by Django 3.1.4 on 2020-12-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.TextField(blank=True, null=True)),
                ('modelo', models.TextField(blank=True, null=True)),
                ('serial', models.TextField(blank=True, null=True)),
                ('fichatécnica', models.TextField(blank=True, db_column='fichaTécnica', null=True)),
                ('url_ft', models.TextField(blank=True, null=True)),
                ('anhofabricacion', models.IntegerField(blank=True, db_column='anhoFabricacion', null=True)),
                ('capacidad', models.FloatField(blank=True, null=True)),
                ('potencia', models.FloatField(blank=True, null=True)),
                ('consumoener', models.FloatField(blank=True, db_column='consumoEner', null=True)),
                ('fuenteener', models.TextField(blank=True, db_column='fuenteEner', null=True)),
                ('stamp_creacion', models.DateTimeField(blank=True, null=True)),
                ('stamp_mod', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoequipo',
            fields=[
                ('tipo', models.TextField(blank=True, null=True)),
                ('fk_norma', models.IntegerField(blank=True, null=True)),
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tipoEquipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidadmedicion',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('sistema', models.TextField(blank=True, null=True)),
                ('unidad', models.TextField(blank=True, null=True)),
                ('simbolo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unidadMedicion',
                'managed': False,
            },
        ),
    ]
