# Generated by Django 3.1.4 on 2020-12-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companhia',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('razonsocial', models.TextField(blank=True, db_column='razonSocial', null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('rfc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companhia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('cp', models.TextField(blank=True, null=True)),
                ('calle', models.TextField(blank=True, null=True)),
                ('numero', models.TextField(blank=True, null=True)),
                ('colonia', models.TextField(blank=True, null=True)),
                ('municipio', models.TextField(blank=True, null=True)),
                ('codigoplus', models.TextField(blank=True, db_column='codigoPlus', null=True)),
                ('utmx', models.FloatField(blank=True, null=True)),
                ('utmy', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('cod', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('nombreoficial', models.TextField(blank=True, db_column='nombreOficial', null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('cod', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('nombreoficial', models.TextField(blank=True, db_column='nombreOficial', null=True)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.TextField(blank=True, null=True)),
                ('apellidos', models.TextField(blank=True, null=True)),
                ('razonsocial', models.TextField(blank=True, db_column='razonSocial', null=True)),
                ('rfc', models.TextField(blank=True, null=True)),
                ('clave', models.CharField(blank=True, max_length=4, null=True)),
                ('fk_titulo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
    ]
