# Generated by Django 3.1.4 on 2021-02-24 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directorio', '0001_initial'),
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(blank=True, max_length=140, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('companhia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directorio.companhia')),
                ('miembro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directorio.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Obs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obs', models.TextField(blank=True, null=True)),
                ('stamp_crea', models.DateTimeField(blank=True, db_column='stampCrea', default=django.utils.timezone.now, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, db_column='stampMod', null=True)),
                ('fk_creador', models.IntegerField(blank=True, null=True)),
                ('fk_modif', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'obs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.TextField(max_length=35)),
                ('nombre', models.TextField()),
                ('plazo_entrega', models.IntegerField(blank=True, null=True, verbose_name='Plazo_días_hábiles')),
                ('fk_tipo_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.tipoproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('clave', models.TextField(default='', max_length=35)),
                ('cliente', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, db_column='fechaInicio', null=True)),
                ('fecha_fin', models.DateField(blank=True, db_column='fechaFin', null=True)),
                ('etapa', models.TextField(blank=True, choices=[('1', 'DISEÑO Y CONSTRUCCION'), ('2', 'OPERACIÓN')], null=True)),
                ('avance', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('fk_obs', models.ManyToManyField(blank=True, to='proyectos.Obs')),
                ('fk_proyecto_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('fk_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='proyectos.tipoproyecto')),
                ('miembros', models.ManyToManyField(through='proyectos.Brigada', to='directorio.Persona')),
                ('predios', models.ManyToManyField(blank=True, to='espacios.Predio')),
            ],
            options={
                'db_table': 'proyectos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='brigada',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
    ]
