# Generated by Django 3.1.4 on 2020-12-16 03:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20201216_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='clave',
            field=models.TextField(default='', max_length=35),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fk_proyectopadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(default='proy', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='stampcrea',
            field=models.DateTimeField(blank=True, db_column='stampCrea', default=datetime.datetime.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='stampmod',
            field=models.DateTimeField(auto_now_add=True, db_column='stampMod', null=True),
        ),
    ]
