# Generated by Django 3.1.4 on 2020-12-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_auto_20201227_1727'),
        ('proyectos', '0005_auto_20201217_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(blank=True, max_length=140, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('companhia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.companhia')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.persona')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='miembros',
            field=models.ManyToManyField(through='proyectos.Brigada', to='directorio.Persona'),
        ),
    ]
