# Generated by Django 3.1.4 on 2020-12-28 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0003_persona_usuario'),
        ('proyectos', '0006_auto_20201227_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigada',
            name='companhia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directorio.companhia'),
        ),
        migrations.AlterField(
            model_name='brigada',
            name='miembro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directorio.persona'),
        ),
    ]
