# Generated by Django 3.1.4 on 2021-01-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_auto_20201228_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='estado',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='etapa',
            field=models.TextField(blank=True, choices=[('1', 'DISEÑO Y CONSTRUCCION'), ('2', 'OPERACIÓN')], null=True),
        ),
    ]
