# Generated by Django 3.1.4 on 2021-01-14 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_auto_20210113_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproyecto',
            name='fk_tipo_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.tipoproyecto'),
        ),
    ]
