# Generated by Django 3.1.4 on 2021-01-15 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_tipoproyecto_fk_tipo_padre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areasproy',
            options={},
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='stamp_crea',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='stamp_mod',
        ),
    ]
