# Generated by Django 3.1.4 on 2021-01-17 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_auto_20210115_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areasproy',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='obs',
            options={'managed': True},
        ),
    ]
