# Generated by Django 3.1.4 on 2021-01-17 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_auto_20210117_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areasproy',
            options={},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fk_obs',
            field=models.ManyToManyField(to='proyectos.Obs'),
        ),
        migrations.AlterField(
            model_name='obs',
            name='stampcrea',
            field=models.DateTimeField(blank=True, db_column='stampCrea', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='obs',
            name='stampmod',
            field=models.DateTimeField(auto_now_add=True, db_column='stampMod', null=True),
        ),
    ]
