# Generated by Django 3.1.4 on 2021-01-17 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_auto_20210117_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areasproy',
            old_name='stampcrea',
            new_name='stamp_crea',
        ),
        migrations.RenameField(
            model_name='areasproy',
            old_name='stampmod',
            new_name='stamp_mod',
        ),
        migrations.RenameField(
            model_name='areasproy',
            old_name='supconstbnb',
            new_name='sup_const_bnb',
        ),
        migrations.RenameField(
            model_name='areasproy',
            old_name='supconstsnb',
            new_name='sup_const_snb',
        ),
        migrations.RenameField(
            model_name='areasproy',
            old_name='supdesplante',
            new_name='sup_desplante',
        ),
        migrations.RenameField(
            model_name='areasproy',
            old_name='supotraslibres',
            new_name='sup_otras_libres',
        ),
        migrations.RenameField(
            model_name='areasproy',
            old_name='suppavimentos',
            new_name='sup_pavimentos',
        ),
        migrations.RenameField(
            model_name='areasproy',
            old_name='supverdeimper',
            new_name='sup_verde_imper',
        ),
        migrations.RenameField(
            model_name='areasproy',
            old_name='supverdeperm',
            new_name='sup_verde_perm',
        ),
        migrations.AddField(
            model_name='areasproy',
            name='fk_obs',
            field=models.ManyToManyField(db_column='fk_obs', to='proyectos.Obs'),
        ),
        migrations.AddField(
            model_name='areasproy',
            name='fk_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
        ),
    ]
