# Generated by Django 3.1.4 on 2021-01-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_auto_20210117_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fk_obs',
            field=models.ManyToManyField(blank=True, null=True, to='proyectos.Obs'),
        ),
    ]
