# Generated by Django 3.1.4 on 2021-01-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0016_auto_20210117_0120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Areasproy',
        ),
    ]
