# Generated by Django 3.1.4 on 2021-01-17 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_delete_areasproy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obs',
            name='stampcrea',
            field=models.DateTimeField(blank=True, db_column='stampCrea', default=django.utils.timezone.now, null=True),
        ),
    ]
