# Generated by Django 3.1.4 on 2021-01-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0018_auto_20210117_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obs',
            old_name='stampcrea',
            new_name='stamp_crea',
        ),
        migrations.RenameField(
            model_name='obs',
            old_name='stampmod',
            new_name='stamp_mod',
        ),
    ]
