# Generated by Django 3.1.4 on 2021-01-18 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0019_auto_20210117_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fk_predio',
        ),
    ]
