# Generated by Django 3.1.4 on 2021-01-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0006_remove_predio_proyecto'),
        ('proyectos', '0020_remove_proyecto_fk_predio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='predios',
            field=models.ManyToManyField(blank=True, to='espacios.Predio'),
        ),
    ]
