# Generated by Django 3.1.4 on 2021-01-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0021_proyecto_predios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoproyecto',
            old_name='plazoentrega',
            new_name='plazo_entrega',
        ),
    ]
