# Generated by Django 3.1.4 on 2021-01-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0022_auto_20210118_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obs',
            old_name='pk_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='pk_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tipoproyecto',
            old_name='pk_id',
            new_name='id',
        ),
    ]
