# Generated by Django 3.1.4 on 2021-01-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0023_auto_20210121_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
