# Generated by Django 3.1.4 on 2020-12-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('sup', models.FloatField(blank=True, null=True)),
                ('nivel', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('supdesp', models.FloatField(blank=True, db_column='supDesp', null=True)),
                ('supconst', models.FloatField(blank=True, db_column='supConst', null=True)),
                ('alturasnb', models.FloatField(blank=True, db_column='alturaSNB', null=True)),
            ],
            options={
                'db_table': 'espacio',
                'managed': False,
            },
        ),
    ]
