# Generated by Django 3.1.4 on 2021-02-24 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Companhia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.TextField(blank=True, db_column='razonSocial', null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('rfc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companhia',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=3)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('nombre_oficial', models.TextField(blank=True, db_column='nombreOficial', null=True)),
            ],
            options={
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.TextField(blank=True, null=True)),
                ('apellidos', models.TextField(blank=True, null=True)),
                ('razon_social', models.TextField(blank=True, db_column='razonSocial', null=True)),
                ('rfc', models.TextField(blank=True, null=True)),
                ('clave', models.CharField(blank=True, max_length=4, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(blank=True, max_length=3, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('nombre_oficial', models.TextField(blank=True, db_column='nombreOficial', null=True)),
                ('fk_pais', models.ForeignKey(blank=True, db_column='fk_pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directorio.pais')),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cp', models.TextField(blank=True, null=True)),
                ('calle', models.TextField(blank=True, null=True)),
                ('numero', models.TextField(blank=True, null=True)),
                ('colonia', models.TextField(blank=True, null=True)),
                ('municipio', models.TextField(blank=True, null=True)),
                ('codigo_plus', models.TextField(blank=True, db_column='codigoPlus', null=True)),
                ('utm_x', models.FloatField(blank=True, null=True)),
                ('utm_y', models.FloatField(blank=True, null=True)),
                ('estado', models.ForeignKey(blank=True, db_column='fk_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directorio.estado')),
            ],
            options={
                'db_table': 'direccion',
            },
        ),
    ]
