# Generated by Django 3.1.4 on 2020-12-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': True},
        ),
    ]
