# Generated by Django 3.1.4 on 2021-01-15 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0003_persona_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fk_titulo',
        ),
    ]
