# Generated by Django 3.1.4 on 2021-01-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0004_remove_persona_fk_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='razonsocial',
            new_name='razon_social',
        ),
    ]
