# Generated by Django 3.1.4 on 2021-01-17 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0005_auto_20210117_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companhia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={},
        ),
    ]
