# Generated by Django 3.1.4 on 2021-01-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0007_auto_20210117_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='codigoplus',
            new_name='codigo_plus',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='utmx',
            new_name='utm_x',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='utmy',
            new_name='utm_y',
        ),
        migrations.AlterField(
            model_name='pais',
            name='clave',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
