# Generated by Django 3.1.4 on 2021-01-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0008_auto_20210118_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companhia',
            old_name='pk_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='pk_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='estado',
            old_name='pk_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='pk_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='pk_id',
            new_name='id',
        ),
    ]
