# Generated by Django 3.1.4 on 2021-01-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertEvidReq',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(blank=True, max_length=10, null=True)),
                ('requerimiento', models.TextField(blank=True, null=True)),
                ('aplica_dc', models.BooleanField(blank=True, null=True)),
                ('aplica_op', models.BooleanField(blank=True, null=True)),
                ('fk_criterio_padre', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cert_evid_req',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=140, null=True)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('aplica_dc', models.BooleanField(blank=True, null=True)),
                ('aplica_op', models.BooleanField(blank=True, null=True)),
                ('obligatorio_dc', models.BooleanField(blank=True, null=True)),
                ('puntos_dc', models.IntegerField(blank=True, null=True)),
                ('obligatorio_op', models.BooleanField(blank=True, null=True)),
                ('puntos_op', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cert_criterio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenciaReq',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('evidencia_req', models.TextField()),
            ],
            options={
                'db_table': 'cert_evidencia_req',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('rubro', models.CharField(max_length=70)),
                ('clave', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'cert_rubro',
                'managed': False,
            },
        ),
    ]
