# Generated by Django 3.1.4 on 2021-02-24 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('proyecto', models.OneToOneField(limit_choices_to={'fk_tipo': 4}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='proyecto_cert', serialize=False, to='proyectos.proyecto')),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(blank=True, max_length=5, null=True)),
                ('nombre', models.CharField(blank=True, max_length=140, null=True)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('aplica_dc', models.BooleanField(blank=True, null=True)),
                ('aplica_op', models.BooleanField(blank=True, null=True)),
                ('obligatorio_dc', models.BooleanField(blank=True, null=True)),
                ('puntos_dc', models.IntegerField(blank=True, null=True)),
                ('obligatorio_op', models.BooleanField(blank=True, null=True)),
                ('puntos_op', models.IntegerField(blank=True, null=True)),
                ('aplica_tipo_proyecto', models.ManyToManyField(blank=True, to='proyectos.TipoProyecto')),
            ],
            options={
                'db_table': 'cert_criterio',
                'ordering': ['id', 'clave'],
            },
        ),
        migrations.CreateModel(
            name='CriterioProyecto',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participa', models.BooleanField(blank=True, default=True, null=True)),
                ('cumple', models.TextField(blank=True, choices=[('0', 'No'), ('1', 'Sí'), ('2', 'Posible'), ('3', 'Imposible'), ('4', 'Desconocido')], null=True)),
                ('puntos_obtenidos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['fk_proyecto', 'fk_criterio'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaCriterio',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aplica_dc', models.BooleanField(blank=True, null=True)),
                ('aplica_op', models.BooleanField(blank=True, null=True)),
                ('fk_criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.criterio')),
            ],
            options={
                'ordering': ['fk_criterio', 'fk_evidencia_req'],
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(blank=True, max_length=20, null=True)),
                ('clave_sedema', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_requerido', models.FloatField(blank=True, null=True)),
                ('definicion', models.TextField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['clave_sedema'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meta', models.TextField(blank=True, null=True)),
                ('aplica_dc', models.BooleanField(blank=True, null=True)),
                ('aplica_op', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('req', models.TextField(blank=True, null=True)),
                ('req_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reqpadre', to='certificaciones.requerimiento')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('rubro', models.CharField(max_length=70)),
                ('clave', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'cert_rubro',
            },
        ),
        migrations.CreateModel(
            name='RequerimientoProyecto',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cumple', models.TextField(blank=True, choices=[('0', 'No'), ('1', 'Sí'), ('2', 'Posible'), ('3', 'Imposible'), ('4', 'Desconocido')], null=True)),
                ('fk_criterio_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.criterioproyecto')),
                ('fk_obs', models.ManyToManyField(blank=True, to='proyectos.Obs')),
                ('fk_req', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificaciones.requerimiento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicadorProyecto',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_indicador', models.FloatField(blank=True, null=True)),
                ('cumple', models.TextField(blank=True, choices=[('0', 'No'), ('1', 'Sí'), ('2', 'Posible'), ('3', 'Imposible'), ('4', 'Desconocido')], null=True)),
                ('fk_criterio_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.criterioproyecto')),
                ('fk_indicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificaciones.indicador')),
                ('fk_obs', models.ManyToManyField(blank=True, to='proyectos.Obs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenciaReq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evidencia_req', models.TextField()),
                ('fk_evid_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificaciones.evidenciareq')),
            ],
            options={
                'ordering': ['evidencia_req'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaProyecto',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cumple', models.TextField(blank=True, choices=[('0', 'No'), ('1', 'Sí'), ('2', 'Posible'), ('3', 'Imposible'), ('4', 'Desconocido')], null=True)),
                ('evidencia_presentada', models.CharField(blank=True, max_length=140, null=True)),
                ('fk_criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.criterioproyecto')),
                ('fk_evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.evidenciacriterio')),
                ('fk_obs', models.ManyToManyField(blank=True, to='proyectos.Obs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='evidenciacriterio',
            name='fk_evidencia_req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.evidenciareq'),
        ),
        migrations.AddField(
            model_name='evidenciacriterio',
            name='fk_obs',
            field=models.ManyToManyField(blank=True, to='proyectos.Obs'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='evidencias',
            field=models.ManyToManyField(related_name='cert_evid', through='certificaciones.EvidenciaProyecto', to='certificaciones.EvidenciaCriterio'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='fk_criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.criterio'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='fk_obs',
            field=models.ManyToManyField(blank=True, to='proyectos.Obs'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='fk_proyecto',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='certificaciones.certificacion'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='indicadores',
            field=models.ManyToManyField(blank=True, related_name='cert_ind', through='certificaciones.IndicadorProyecto', to='certificaciones.Indicador'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='requerimientos',
            field=models.ManyToManyField(blank=True, related_name='cert_req', through='certificaciones.RequerimientoProyecto', to='certificaciones.Requerimiento'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='evidencias',
            field=models.ManyToManyField(through='certificaciones.EvidenciaCriterio', to='certificaciones.EvidenciaReq'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='fk_obs',
            field=models.ManyToManyField(blank=True, to='proyectos.Obs'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='fk_rubro',
            field=models.ForeignKey(blank=True, db_column='fk_rubro', null=True, on_delete=django.db.models.deletion.CASCADE, to='certificaciones.rubro'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='indicadores',
            field=models.ManyToManyField(blank=True, related_name='criterio_ind', to='certificaciones.Indicador'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='metas',
            field=models.ManyToManyField(blank=True, to='certificaciones.Meta'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='requerimientos',
            field=models.ManyToManyField(blank=True, related_name='criterio_req', to='certificaciones.Requerimiento'),
        ),
        migrations.AddField(
            model_name='certificacion',
            name='criterios',
            field=models.ManyToManyField(through='certificaciones.CriterioProyecto', to='certificaciones.Criterio'),
        ),
    ]
