# Generated by Django 3.1.4 on 2021-01-13 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_auto_20201228_0235'),
        ('certificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioProyecto',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('cumple', models.BooleanField(blank=True, null=True)),
                ('puntos_obtenidos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenciaCriterio',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('aplica_dc', models.BooleanField(blank=True, null=True)),
                ('aplica_op', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenciaCriterioProy',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('cumple', models.BooleanField(blank=True, null=True)),
                ('fk_criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.criterioproyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('pk_id', models.OneToOneField(limit_choices_to={'pk_tipo': 1}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='proyecto_cert', serialize=False, to='proyectos.proyecto')),
            ],
        ),
        migrations.DeleteModel(
            name='CertEvidReq',
        ),
        migrations.AlterModelOptions(
            name='criterio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='evidenciareq',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rubro',
            options={},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='criterios',
            field=models.ManyToManyField(through='certificaciones.CriterioProyecto', to='certificaciones.Criterio'),
        ),
        migrations.AddField(
            model_name='evidenciacriterioproy',
            name='fk_evidencia_req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.evidenciareq'),
        ),
        migrations.AddField(
            model_name='evidenciacriterioproy',
            name='fk_obs',
            field=models.ForeignKey(blank=True, db_column='fk_obs', null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.obs'),
        ),
        migrations.AddField(
            model_name='evidenciacriterio',
            name='fk_criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.criterio'),
        ),
        migrations.AddField(
            model_name='evidenciacriterio',
            name='fk_evidencia_req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.evidenciareq'),
        ),
        migrations.AddField(
            model_name='evidenciacriterio',
            name='fk_obs',
            field=models.ForeignKey(blank=True, db_column='fk_obs', null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.obs'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='evidencias',
            field=models.ManyToManyField(through='certificaciones.EvidenciaCriterioProy', to='certificaciones.EvidenciaReq'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='fk_criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.criterio'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='fk_obs',
            field=models.ForeignKey(blank=True, db_column='fk_obs', null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.obs'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='fk_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.proyecto'),
        ),
    ]
