# Generated by Django 3.1.4 on 2021-01-13 19:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_auto_20210113_1926'),
        ('certificaciones', '0002_auto_20210113_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='evidencias',
            field=models.ManyToManyField(through='certificaciones.EvidenciaCriterio', to='certificaciones.EvidenciaReq'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='fk_obs',
            field=models.ForeignKey(blank=True, db_column='fk_obs', null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.obs'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='fk_rubro',
            field=models.ForeignKey(blank=True, db_column='fk_rubro', null=True, on_delete=django.db.models.deletion.CASCADE, to='certificaciones.Rubro'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='stamp_crea',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='criterio',
            name='stamp_mod',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterModelTable(
            name='evidenciareq',
            table=None,
        ),
    ]
