# Generated by Django 3.1.4 on 2021-01-15 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_auto_20210115_0141'),
        ('certificaciones', '0003_auto_20210113_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterioproyecto',
            name='fk_obs',
        ),
        migrations.RemoveField(
            model_name='evidenciacriterio',
            name='fk_obs',
        ),
        migrations.RemoveField(
            model_name='evidenciacriterioproy',
            name='fk_obs',
        ),
        migrations.AddField(
            model_name='evidenciareq',
            name='fk_evid_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificaciones.evidenciareq'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='pk_id',
            field=models.OneToOneField(limit_choices_to={'pk_tipo': 4}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='proyecto_cert', serialize=False, to='proyectos.proyecto'),
        ),
    ]
