# Generated by Django 3.1.4 on 2021-01-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0004_auto_20210115_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidenciacriterio',
            options={'ordering': ['fk_criterio', 'fk_evidencia_req']},
        ),
    ]
