# Generated by Django 3.1.4 on 2021-01-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_delete_areasproy'),
        ('certificaciones', '0005_auto_20210116_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterioproyecto',
            name='fk_obs',
            field=models.ManyToManyField(blank=True, to='proyectos.Obs'),
        ),
        migrations.AddField(
            model_name='evidenciacriterio',
            name='fk_obs',
            field=models.ManyToManyField(blank=True, to='proyectos.Obs'),
        ),
        migrations.AddField(
            model_name='evidenciacriterioproy',
            name='fk_obs',
            field=models.ManyToManyField(blank=True, to='proyectos.Obs'),
        ),
        migrations.RemoveField(
            model_name='criterio',
            name='fk_obs',
        ),
        migrations.AddField(
            model_name='criterio',
            name='fk_obs',
            field=models.ManyToManyField(blank=True, to='proyectos.Obs'),
        ),
    ]
