# Generated by Django 3.1.4 on 2021-01-17 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0006_auto_20210117_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='stamp_crea',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='criterioproyecto',
            name='stamp_crea',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='evidenciacriterio',
            name='stamp_crea',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='evidenciacriterioproy',
            name='stamp_crea',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
