# Generated by Django 3.1.4 on 2021-01-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0022_auto_20210118_1201'),
        ('certificaciones', '0007_auto_20210117_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='aplica_tipo_proyecto',
            field=models.ManyToManyField(blank=True, to='proyectos.TipoProyecto'),
        ),
    ]
