# Generated by Django 3.1.4 on 2021-01-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0008_criterio_aplica_tipo_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='indicador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criterio',
            name='meta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criterio',
            name='requerimiento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
