# Generated by Django 3.1.4 on 2021-01-20 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0009_auto_20210118_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterio',
            name='requerimiento',
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('req', models.TextField(blank=True, null=True)),
                ('req_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reqpadre', to='certificaciones.requerimiento')),
            ],
        ),
        migrations.AddField(
            model_name='criterio',
            name='requerimientos',
            field=models.ManyToManyField(blank=True, related_name='criterio', to='certificaciones.Requerimiento'),
        ),
    ]
