# Generated by Django 3.1.4 on 2021-01-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0011_auto_20210120_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='metas',
            field=models.ManyToManyField(blank=True, to='certificaciones.Meta'),
        ),
    ]
