# Generated by Django 3.1.4 on 2021-01-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0012_auto_20210120_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(blank=True, max_length=20, null=True)),
                ('clave_sedema', models.CharField(blank=True, max_length=20, null=True)),
                ('definicion', models.TextField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
