# Generated by Django 3.1.4 on 2021-01-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0014_auto_20210120_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='clave',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
