# Generated by Django 3.1.4 on 2021-01-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0016_auto_20210120_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificacion',
            old_name='pk_id',
            new_name='proyecto',
        ),
        migrations.RemoveField(
            model_name='criterioproyecto',
            name='cumple',
        ),
        migrations.RemoveField(
            model_name='criterioproyecto',
            name='evidencias',
        ),
        migrations.RemoveField(
            model_name='criterioproyecto',
            name='puntos_obtenidos',
        ),
    ]
