# Generated by Django 3.1.4 on 2021-01-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0018_auto_20210121_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacion',
            name='slug',
            field=models.SlugField(default='pces-2020-rmmir', editable=False),
            preserve_default=False,
        ),
    ]
