# Generated by Django 3.1.4 on 2021-01-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0019_certificacion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterioproyecto',
            name='cumple',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='evidencias',
            field=models.ManyToManyField(related_name='cert_evid', through='certificaciones.EvidenciaCriterioProy', to='certificaciones.EvidenciaReq'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='fk_rubro',
            field=models.ForeignKey(blank=True, db_column='fk_rubro', null=True, on_delete=django.db.models.deletion.CASCADE, to='certificaciones.rubro'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='indicadores',
            field=models.ManyToManyField(blank=True, related_name='cert_ind', to='certificaciones.Indicador'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='metas',
            field=models.ManyToManyField(blank=True, to='certificaciones.Meta'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='puntos_obtenidos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='requerimientos',
            field=models.ManyToManyField(blank=True, related_name='cert_req', to='certificaciones.Requerimiento'),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='slug',
            field=models.SlugField(),
        ),
    ]
