# Generated by Django 3.1.4 on 2021-01-21 22:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0023_auto_20210121_1542'),
        ('certificaciones', '0020_auto_20210121_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterioproyecto',
            name='evidencias',
        ),
        migrations.RemoveField(
            model_name='criterioproyecto',
            name='fk_rubro',
        ),
        migrations.RemoveField(
            model_name='criterioproyecto',
            name='indicadores',
        ),
        migrations.RemoveField(
            model_name='criterioproyecto',
            name='metas',
        ),
        migrations.RemoveField(
            model_name='criterioproyecto',
            name='requerimientos',
        ),
        migrations.RemoveField(
            model_name='evidenciacriterioproy',
            name='cumple',
        ),
        migrations.RemoveField(
            model_name='evidenciacriterioproy',
            name='fk_evidencia_req',
        ),
        migrations.AddField(
            model_name='evidenciacriterioproy',
            name='fk_evidencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='certificaciones.evidenciacriterio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='criterio',
            name='requerimientos',
            field=models.ManyToManyField(blank=True, related_name='criterio_req', to='certificaciones.Requerimiento'),
        ),
        migrations.CreateModel(
            name='RequerimientoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('cumple', models.BooleanField(blank=True, null=True)),
                ('fk_criterio_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.criterioproyecto')),
                ('fk_obs', models.ManyToManyField(blank=True, to='proyectos.Obs')),
                ('fk_req', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificaciones.requerimiento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicadorProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('valor_indicador', models.FloatField(blank=True, null=True)),
                ('cumple', models.BooleanField(blank=True, null=True)),
                ('fk_criterio_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.criterioproyecto')),
                ('fk_indicador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificaciones.indicador')),
                ('fk_obs', models.ManyToManyField(blank=True, to='proyectos.Obs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenciaProyecto',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('cumple', models.BooleanField(blank=True, null=True)),
                ('evidencia_presentada', models.CharField(blank=True, max_length=140, null=True)),
                ('fk_criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.criterioproyecto')),
                ('fk_evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificaciones.evidenciacriterio')),
                ('fk_obs', models.ManyToManyField(blank=True, to='proyectos.Obs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='evidenciass',
            field=models.ManyToManyField(related_name='cert_evid', through='certificaciones.EvidenciaProyecto', to='certificaciones.EvidenciaCriterio'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='indicadoress',
            field=models.ManyToManyField(blank=True, related_name='cert_ind', through='certificaciones.IndicadorProyecto', to='certificaciones.Indicador'),
        ),
        migrations.AddField(
            model_name='criterioproyecto',
            name='requerimientoss',
            field=models.ManyToManyField(blank=True, related_name='cert_req', through='certificaciones.RequerimientoProyecto', to='certificaciones.Requerimiento'),
        ),
    ]
