# Generated by Django 3.1.4 on 2021-01-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0021_auto_20210121_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criterioproyecto',
            old_name='evidenciass',
            new_name='evidencias',
        ),
        migrations.RenameField(
            model_name='criterioproyecto',
            old_name='indicadoress',
            new_name='indicadores',
        ),
        migrations.RenameField(
            model_name='criterioproyecto',
            old_name='requerimientoss',
            new_name='requerimientos',
        ),
        migrations.DeleteModel(
            name='EvidenciaCriterioProy',
        ),
    ]
