# Generated by Django 3.1.4 on 2021-01-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0022_auto_20210121_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidenciaproyecto',
            old_name='pk_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='indicadorproyecto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requerimientoproyecto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
