# Generated by Django 3.1.4 on 2021-01-22 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0023_auto_20210122_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterioproyecto',
            options={'ordering': ['fk_proyecto', 'fk_criterio']},
        ),
        migrations.RenameField(
            model_name='meta',
            old_name='descripcion',
            new_name='meta',
        ),
    ]
