# Generated by Django 3.1.4 on 2021-01-23 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0024_auto_20210122_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='valor_requerido',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificacion',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='criterioproyecto',
            name='fk_criterio',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='certificaciones.criterio'),
        ),
        migrations.AlterField(
            model_name='criterioproyecto',
            name='fk_proyecto',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='certificaciones.certificacion'),
        ),
        migrations.AlterField(
            model_name='requerimientoproyecto',
            name='fk_req',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificaciones.requerimiento'),
        ),
    ]
