# Generated by Django 3.1.4 on 2021-01-25 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificaciones', '0026_criterioproyecto_participa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidenciareq',
            options={'ordering': ['evidencia_req']},
        ),
        migrations.AlterModelOptions(
            name='indicador',
            options={'ordering': ['clave_sedema']},
        ),
        migrations.AlterModelOptions(
            name='requerimiento',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='criterioproyecto',
            name='cumple',
            field=models.TextField(blank=True, choices=[('0', 'No'), ('1', 'Sí'), ('2', 'Posible'), ('3', 'Imposible'), ('4', 'Desconocido')], null=True),
        ),
        migrations.AlterField(
            model_name='criterioproyecto',
            name='participa',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidenciaproyecto',
            name='cumple',
            field=models.TextField(blank=True, choices=[('0', 'No'), ('1', 'Sí'), ('2', 'Posible'), ('3', 'Imposible'), ('4', 'Desconocido')], null=True),
        ),
        migrations.AlterField(
            model_name='indicadorproyecto',
            name='cumple',
            field=models.TextField(blank=True, choices=[('0', 'No'), ('1', 'Sí'), ('2', 'Posible'), ('3', 'Imposible'), ('4', 'Desconocido')], null=True),
        ),
        migrations.AlterField(
            model_name='requerimientoproyecto',
            name='cumple',
            field=models.TextField(blank=True, choices=[('0', 'No'), ('1', 'Sí'), ('2', 'Posible'), ('3', 'Imposible'), ('4', 'Desconocido')], null=True),
        ),
        migrations.AlterField(
            model_name='requerimientoproyecto',
            name='fk_req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificaciones.requerimiento'),
        ),
    ]
