# Generated by Django 3.1.4 on 2021-01-17 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0019_auto_20210117_0711'),
        ('directorio', '0007_auto_20210117_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedicion',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('sistema', models.TextField(blank=True, null=True)),
                ('unidad', models.TextField(blank=True, null=True)),
                ('simbolo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unidadMedicion',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('tipo', models.TextField(blank=True, null=True)),
                ('fk_norma', models.IntegerField(blank=True, null=True)),
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_supertipo', models.ForeignKey(blank=True, db_column='fk_supertipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos.tipoequipo')),
            ],
            options={
                'db_table': 'tipoEquipo',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.TextField(blank=True, null=True)),
                ('modelo', models.TextField(blank=True, null=True)),
                ('serial', models.TextField(blank=True, null=True)),
                ('ficha_tec', models.TextField(blank=True, null=True)),
                ('url_ft', models.TextField(blank=True, null=True)),
                ('anho_fabricacion', models.IntegerField(blank=True, db_column='anhoFabricacion', null=True)),
                ('capacidad', models.FloatField(blank=True, null=True)),
                ('potencia', models.FloatField(blank=True, null=True)),
                ('consumo_ener', models.FloatField(blank=True, db_column='consumoEner', null=True)),
                ('fuente_ener', models.TextField(blank=True, db_column='fuenteEner', null=True)),
                ('stamp_crea', models.DateTimeField(blank=True, null=True)),
                ('stamp_mod', models.DateTimeField(blank=True, null=True)),
                ('equipo_tipo', models.ForeignKey(blank=True, db_column='fk_equipoTipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipos.tipoequipo')),
                ('fk_equipo_padre', models.ForeignKey(blank=True, db_column='fk_equipoPadre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos.equipo')),
                ('fk_obs', models.ForeignKey(blank=True, db_column='fk_obs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.obs')),
                ('fk_unidad_capacidad', models.ForeignKey(blank=True, db_column='fk_unidadCapacidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eq_capacidad', to='equipos.unidadmedicion')),
                ('fk_unidad_ener', models.ForeignKey(blank=True, db_column='fk_unidadEner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eq_energia', to='equipos.unidadmedicion')),
                ('fk_unidad_potencia', models.ForeignKey(blank=True, db_column='fk_unidadPotencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eq_potencia', to='equipos.unidadmedicion')),
                ('pais_origen', models.ForeignKey(blank=True, db_column='fk_paisOrigen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='directorio.pais', verbose_name='pais')),
            ],
            options={
                'db_table': 'equipo',
            },
        ),
    ]
