# Generated by Django 3.1.4 on 2021-02-24 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.TextField(blank=True, null=True)),
                ('modelo', models.TextField(blank=True, null=True)),
                ('potencia', models.FloatField(blank=True, null=True)),
                ('eficiencia', models.FloatField(blank=True, null=True, verbose_name='%η')),
                ('fuente_ener', models.TextField(blank=True, choices=[('0', 'electricidad'), ('1', 'diesel'), ('2', 'gas natural'), ('3', 'gas LP'), ('4', 'gasolina')], db_column='fuenteEner', null=True)),
                ('ficha_tec', models.TextField(blank=True, null=True)),
                ('url_ft', models.TextField(blank=True, null=True)),
                ('anho_fabricacion', models.IntegerField(blank=True, db_column='anhoFabricacion', null=True, verbose_name='año fabricación')),
            ],
            options={
                'verbose_name': 'equipo general',
                'verbose_name_plural': 'equipos generales',
            },
        ),
        migrations.CreateModel(
            name='EquipoProyecto',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.TextField(blank=True, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('sistema', models.CharField(blank=True, max_length=70, null=True)),
                ('foto', models.CharField(blank=True, max_length=140, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sistema', models.TextField(blank=True, choices=[('0', 'SI'), ('1', 'BU')], null=True)),
                ('unidad', models.TextField(blank=True, null=True)),
                ('simbolo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'unidades',
            },
        ),
        migrations.CreateModel(
            name='MotorElectrico',
            fields=[
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipos.equipo')),
                ('rpm', models.FloatField(blank=True, null=True)),
                ('frame', models.CharField(blank=True, max_length=20, null=True)),
                ('frame_type', models.TextField(blank=True, choices=[('0', 'abierto'), ('1', 'cerrado')], null=True)),
                ('poles', models.FloatField(blank=True, null=True)),
                ('voltaje', models.FloatField(blank=True, null=True, verbose_name='V')),
                ('amperaje', models.FloatField(blank=True, null=True, verbose_name='A')),
                ('frecuencia', models.FloatField(blank=True, null=True, verbose_name='Hz')),
                ('nema_premium', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'motor eléctrico',
                'verbose_name_plural': 'motores eléctricos',
            },
            bases=('equipos.equipo',),
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('tipo', models.TextField(blank=True, null=True)),
                ('clave', models.CharField(blank=True, max_length=20, null=True)),
                ('fk_norma', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_supertipo', models.ForeignKey(blank=True, db_column='fk_supertipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos.tipoequipo')),
            ],
        ),
        migrations.CreateModel(
            name='NormaEquipo',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requerimiento', models.FloatField(blank=True, null=True)),
                ('descripcion_requerimimiento', models.CharField(blank=True, max_length=70, null=True)),
                ('cumple', models.TextField(blank=True, choices=[('0', 'No'), ('1', 'Sí'), ('2', 'Posible'), ('3', 'Imposible'), ('4', 'Desconocido')], null=True)),
                ('fk_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
