# Generated by Django 3.1.4 on 2021-02-24 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0002_auto_20210224_1130'),
        ('normas', '0001_initial'),
        ('directorio', '0001_initial'),
        ('equipos', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaequipo',
            name='fk_norma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='normas.norma'),
        ),
        migrations.AddField(
            model_name='normaequipo',
            name='fk_obs',
            field=models.ManyToManyField(blank=True, to='proyectos.Obs'),
        ),
        migrations.AddField(
            model_name='equipoproyecto',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='equipoproyecto',
            name='espacios',
            field=models.ManyToManyField(blank=True, related_name='equipo_esp', to='espacios.Espacio'),
        ),
        migrations.AddField(
            model_name='equipoproyecto',
            name='fk_obs',
            field=models.ManyToManyField(blank=True, to='proyectos.Obs'),
        ),
        migrations.AddField(
            model_name='equipoproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_proy', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='equipo_padre',
            field=models.ForeignKey(blank=True, db_column='fk_equipoPadre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_hijo', to='equipos.equipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='equipo_tipo',
            field=models.ForeignKey(blank=True, db_column='fk_equipoTipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipos.tipoequipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fk_obs',
            field=models.ManyToManyField(blank=True, to='proyectos.Obs'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='normas',
            field=models.ManyToManyField(blank=True, related_name='equipo_norma', through='equipos.NormaEquipo', to='normas.Norma'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='pais_origen',
            field=models.ForeignKey(blank=True, db_column='fk_paisOrigen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='directorio.pais', verbose_name='pais'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='unidad_potencia',
            field=models.ForeignKey(blank=True, db_column='fk_unidadPotencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eq_potencia', to='equipos.unidadmedicion'),
        ),
    ]
