# Generated by Django 3.1.4 on 2021-02-16 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0002_auto_20210119_2252'),
        ('espacios', '0009_auto_20210121_1546'),
        ('proyectos', '0024_auto_20210125_2256'),
        ('equipos', '0002_auto_20210117_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='anho_fabricacion',
            field=models.IntegerField(blank=True, db_column='anhoFabricacion', null=True, verbose_name='año fabricación'),
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='fk_obs',
        ),
        migrations.AddField(
            model_name='equipo',
            name='fk_obs',
            field=models.ManyToManyField(blank=True, to='proyectos.Obs'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='stamp_crea',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='stamp_mod',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='NormaEquipo',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requerimiento', models.FloatField(blank=True, null=True)),
                ('descripcion_requerimimiento', models.CharField(blank=True, max_length=70, null=True)),
                ('cumple', models.TextField(blank=True, choices=[('0', 'No'), ('1', 'Sí'), ('2', 'Posible'), ('3', 'Imposible'), ('4', 'Desconocido')], null=True)),
                ('fk_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo')),
                ('fk_normal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='normas.norma')),
                ('fk_obs', models.ManyToManyField(blank=True, to='proyectos.Obs')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipoProyecto',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('espacios', models.ManyToManyField(blank=True, related_name='equipo_esp', to='espacios.Espacio')),
                ('fk_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo')),
                ('fk_obs', models.ManyToManyField(blank=True, to='proyectos.Obs')),
                ('fk_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_proy', to='proyectos.proyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='normas',
            field=models.ManyToManyField(blank=True, related_name='equipo_norma', through='equipos.NormaEquipo', to='normas.Norma'),
        ),
    ]
