# Generated by Django 3.1.4 on 2021-02-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_auto_20210216_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='fk_equipo_padre',
            new_name='equipo_padre',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='fk_unidad_capacidad',
            new_name='unidad_capacidad',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='fk_unidad_ener',
            new_name='unidad_ener',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='fk_unidad_potencia',
            new_name='unidad_potencia',
        ),
    ]
