# Generated by Django 3.1.4 on 2021-02-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_equipoproyecto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipo',
            name='clave',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
