# Generated by Django 3.1.4 on 2021-02-16 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0008_tipoequipo_clave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.OneToOneField(limit_choices_to={'equipo_tipo.tipo_padre.clave': 'MTR'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='equipos.equipo')),
                ('rpm', models.FloatField(blank=True, null=True)),
                ('frame', models.CharField(blank=True, max_length=20, null=True)),
                ('frame_type', models.TextField(blank=True, choices=[('0', 'abierto'), ('1', 'cerrado')], null=True)),
                ('poles', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
