# Generated by Django 3.1.4 on 2021-02-16 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0009_motor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorElectrico',
            fields=[
                ('equipo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipos.equipo')),
                ('rpm', models.FloatField(blank=True, null=True)),
                ('frame', models.CharField(blank=True, max_length=20, null=True)),
                ('frame_type', models.TextField(blank=True, choices=[('0', 'abierto'), ('1', 'cerrado')], null=True)),
                ('poles', models.FloatField(blank=True, null=True)),
                ('voltaje', models.FloatField(blank=True, null=True, verbose_name='V')),
                ('amperaje', models.FloatField(blank=True, null=True, verbose_name='A')),
                ('frecuencia', models.FloatField(blank=True, null=True, verbose_name='Hz')),
                ('nema_premium', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('equipos.equipo',),
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='consumo_ener',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='unidad_capacidad',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='unidad_ener',
        ),
        migrations.AddField(
            model_name='equipo',
            name='eficiencia',
            field=models.FloatField(blank=True, null=True, verbose_name='η'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='equipo_padre',
            field=models.ForeignKey(blank=True, db_column='fk_equipoPadre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_hijo', to='equipos.equipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fuente_ener',
            field=models.TextField(blank=True, choices=[('0', 'electricidad'), ('1', 'diesel'), ('2', 'gas natural'), ('3', 'gas LP'), ('4', 'gasolina')], db_column='fuenteEner', null=True),
        ),
        migrations.DeleteModel(
            name='Motor',
        ),
    ]
