# Generated by Django 3.1.4 on 2021-02-16 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0010_auto_20210216_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorelectrico',
            options={'verbose_name': 'motor eléctrico', 'verbose_name_plural': 'motores eléctricos'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedicion',
            options={'verbose_name_plural': 'unidades'},
        ),
        migrations.RemoveField(
            model_name='motorelectrico',
            name='equipo_ptr',
        ),
        migrations.AddField(
            model_name='motorelectrico',
            name='equipo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipos.equipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='eficiencia',
            field=models.FloatField(blank=True, null=True, verbose_name='%η'),
        ),
    ]
