# Generated by Django 3.1.4 on 2021-02-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0011_auto_20210216_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name': 'equipo general', 'verbose_name_plural': 'equipos generales'},
        ),
        migrations.AddField(
            model_name='equipoproyecto',
            name='sistema',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
