# Generated by Django 3.1.4 on 2021-02-24 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmisorAmbito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, choices=[('1', 'Libro'), ('2', 'Título'), ('3', 'Capítulo'), ('4', 'Sección'), ('5', 'Art.'), ('6', 'P.'), ('7', 'Apartado'), ('8', 'fr.'), ('9', 'inciso')], max_length=60, null=True)),
                ('numero', models.CharField(blank=True, max_length=40, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('seccion_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='normas.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('stamp_crea', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('stamp_mod', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competencia', models.CharField(blank=True, choices=[('1', 'estatal'), ('2', 'municipal'), ('3', 'federal'), ('4', 'internacional')], max_length=10)),
                ('tipo', models.CharField(blank=True, choices=[('1', 'NOM'), ('2', 'NADF'), ('3', 'NMX'), ('4', 'NTC'), ('5', 'NTEA'), ('6', 'PROY-NOM'), ('10', 'Ley'), ('20', 'Reglamento'), ('100', 'Otro')], max_length=10, null=True)),
                ('rubro', models.CharField(blank=True, max_length=10, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('anho', models.CharField(blank=True, max_length=10, null=True)),
                ('clave', models.CharField(blank=True, max_length=140, null=True)),
                ('nombre', models.CharField(blank=True, max_length=280, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('emisor_ambito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='normas.emisorambito')),
                ('fk_obs', models.ManyToManyField(blank=True, to='proyectos.Obs')),
                ('secciones', models.ManyToManyField(blank=True, to='normas.Seccion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
