# Generated by Django 3.1.4 on 2021-01-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norma',
            name='competencia',
            field=models.CharField(blank=True, choices=[('1', 'estatal'), ('2', 'municipal'), ('3', 'federal'), ('4', 'internacional')], max_length=10),
        ),
        migrations.AlterField(
            model_name='norma',
            name='rubro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='norma',
            name='tipo',
            field=models.CharField(blank=True, choices=[('1', 'NOM'), ('2', 'NADF'), ('3', 'NMX'), ('4', 'NTC'), ('5', 'NTEA'), ('6', 'PROY-NOM'), ('10', 'Ley'), ('20', 'Reglamento'), ('100', 'Otro')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Rubro',
        ),
    ]
