# Generated by Django 3.1.4 on 2021-02-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0002_auto_20210119_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norma',
            name='secciones',
            field=models.ManyToManyField(blank=True, to='normas.Seccion'),
        ),
    ]
